version: "3.0"
services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "80:80"
      - "45341:45341"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y